In [5]:
import pandas as pd

dataset = pd.read_csv("../data/auto_mpg.csv")
dataset.head()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
0,18.0,8,307.0,130.0,3504.0,12.0,70,1
1,15.0,8,350.0,165.0,3693.0,11.5,70,1
2,18.0,8,318.0,150.0,3436.0,11.0,70,1
3,16.0,8,304.0,150.0,3433.0,12.0,70,1
4,17.0,8,302.0,140.0,3449.0,10.5,70,1

In [6]:
dataset.shape

(398, 8)

In [7]:
dataset.isna().sum()

MPG             0
Cylinders       0
Displacement    0
Horsepower      6
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

In [8]:
dataset = dataset.dropna()
dataset.isna().sum()

MPG             0
Cylinders       0
Displacement    0
Horsepower      0
Weight          0
Acceleration    0
Model Year      0
Origin          0
dtype: int64

In [9]:
dataset.Origin.value_counts()

Origin
1    245
3     79
2     68
Name: count, dtype: int64

In [11]:
dataset["Origin"] = dataset["Origin"].map(
    {   
        1: "USA", 
        2: "Europe", 
        3: "Japan",
    },
)
dataset.head(20)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model Year,Origin
0,18.0,8,307.0,130.0,3504.0,12.0,70,NaN
1,15.0,8,350.0,165.0,3693.0,11.5,70,NaN
2,18.0,8,318.0,150.0,3436.0,11.0,70,NaN
3,16.0,8,304.0,150.0,3433.0,12.0,70,NaN
4,17.0,8,302.0,140.0,3449.0,10.5,70,NaN
5,15.0,8,429.0,198.0,4341.0,10.0,70,NaN
6,14.0,8,454.0,220.0,4354.0,9.0,70,NaN
7,14.0,8,440.0,215.0,4312.0,8.5,70,NaN
8,14.0,8,455.0,225.0,4425.0,10.0,70,NaN
9,15.0,8,390.0,190.0,3850.0,8.5,70,NaN
10,15.0,8,383.0,170.0,3563.0,10.0,70,NaN
11,14.0,8,340.0,160.0,3609.0,8.0,70,NaN
12,15.0,8,400.0,150.0,3761.0,9.5,70,NaN
13,14.0,8,455.0,225.0,3086.0,10.0,70,NaN
14,24.0,4,113.0,95.0,2372.0,15.0,70,NaN
15,22.0,6,198.0,95.0,2833.0,15.5,70,NaN
16,18.0,6,199.0,97.0,2774.0,15.5,70,NaN
17,21.0,6,200.0,85.0,2587.0,16.0,70,NaN
18,27.0,4,97.0,88.0,2130.0,14.5,70,NaN
19,26.0,4,97.0,46.0,1835.0,20.5,70,NaN

In [12]:
dataset = pd.get_dummies(dataset, columns=["Origin"], prefix="", prefix_sep="")
dataset.head()

    MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  Model Year
0  18.0          8         307.0       130.0  3504.0          12.0          70
1  15.0          8         350.0       165.0  3693.0          11.5          70
2  18.0          8         318.0       150.0  3436.0          11.0          70
3  16.0          8         304.0       150.0  3433.0          12.0          70
4  17.0          8         302.0       140.0  3449.0          10.5          70